spring:
  profiles:
      active: dev

---
# 开发环境
server:
    port: 8090
spring:
    profiles: dev
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/xuebin_blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
        name: xuebin_blog
        username: root
        password: 123456
        dbcp2:
            test-on-return: false
            test-on-borrow: true
            test-while-idle: true
            validation-query: SELECT 1
    jpa:
#        database-platform: xuebin.blog.utils.FixedMySQLInnoDBDialect
        database: MYSQL
        show_sql: true
        hibernate:
            ddl-auto: update
    http:
        encoding:
            force: true
            charset: UTF-8
            enabled: true
    resources:
      static-locations: classpath:templates/,classpath:static/
    thymeleaf:
      cache: false
    mvc:
        static-path-pattern: /**
        view:
          suffix: .html

---
# 生产环境
server:
    port: 80
spring:
    profiles: prod
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/xuebin_blog?useUnicode=true&characterEncoding=utf8mb4&autoReconnect=true&zeroDateTimeBehavior=convertToNull
        name: xuebin_blog
        username: root
        password: 123456
        dbcp2:
            test-on-return: false
            test-on-borrow: true
            test-while-idle: true
            validation-query: SELECT 1
    jpa:
        database-platform: xuebin.blog.utils.FixedMySQLInnoDBDialect
        database: MYSQL
        show_sql: false
        hibernate:
            ddl-auto: none
    http:
        encoding:
            force: true
            charset: UTF-8
            enabled: true
    thymeleaf:
      cache: false

    mvc:
        static-path-pattern: /**